.TH RENAMEBYREPLACE 1 2018\-11\-22
.SH NAME

.B renamebyreplace:
Rename files replacing subtrings in filename
.SH SYNOPSIS

renamebyreplace usage: renamebyreplace [\-h] [\-\-search SEARCH] [\-\-replace REPLACE] [\-\-write]
.SH LA DESCRIPTION

.PP
Cette application a les paramètres obligatoires suivants :
.PP
.RS
.B \-\-search
.RE
.PP
.RS
.RS
Search this substring in the filename
.RE
.RE
.PP
.RS
.B \-\-replace
.RE
.PP
.RS
.RS
Replace search substring with this substring
.RE
.RE
.PP
.RS
If you want to write changes in filesystem you must add \-\-write parameter
.RE
.SH EXEMPLES

.PP
.RS
.B Pretend example
.RE
.PP
.RS
.RS
renamebyreplace \-\-search ABCD \-\-replace Abcd
.RE
.RE
.PP
.RS
.RS
This comand pretends the renaming
.RE
.RE
.PP
.RS
.B Write Example
.RE
.PP
.RS
.RS
renamebyreplace \-\-search ABCD \-\-replace Abcd \-\-writes
.RE
.RE
.PP
.RS
.RS
This comand makes the renaming
.RE
.RE
