.TH RENAMEBYREPLACE 1 2019\-02\-01
.SH NAME

.B renamebyreplace:
Renombra ficheros sustituyendo cadenas en el nombre del fichero
.SH SYNOPSIS

renamebyreplace usage: renamebyreplace [\-h] [\-\-search SEARCH] [\-\-replace REPLACE] [\-\-write] [\-\-undo]
.SH DESCRIPCI\('ON

.PP
Esta aplicaci\('on tiene los siguientes par\('ametros obligatorios
.PP
.RS
.B \-\-search
.RE
.PP
.RS
.RS
Busca esta cadena en el nombre del fichero
.RE
.RE
.PP
.RS
.B \-\-replace
.RE
.PP
.RS
.RS
Sustituye la cadena buscada con esta otra
.RE
.RE
.PP
.RS
.B \-\-undo
.RE
.PP
Uses the \-\-search argument as the \-\-replace one and the \-\-replace argument as the \-\-search one
.PP
.RS
If you want to write changes in filesystem you must add \-\-write parameter
.RE
.SH EJEMPLOS

.PP
.RS
.B Ejemplo de simulaci\('on
.RE
.PP
.RS
.RS
renamebyreplace \-\-search ABCD \-\-replace Abcd
.RE
.RE
.PP
.RS
.RS
Este comando simula el renombrado
.RE
.RE
.PP
.RS
.B Ejemplo de escritura
.RE
.PP
.RS
.RS
renamebyreplace \-\-search ABCD \-\-replace Abcd \-\-writes
.RE
.RE
.PP
.RS
.RS
Este comando realiza el renombrado
.RE
.RE
